name: Build & Deploy frontend
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Build React App
        run: npm run build
        env:
          VITE_PUBLIC_API_URL: "https://www.chalochutti.com/followupdeskapi"
          

      - name: Remove old dist folder (if exists)
        run: |
          if [ -d /var/www/html/followupdesk/dist ]; then
            echo "Old dist folder found. Removing..."
            rm -rf /var/www/html/followupdesk/dist
          else
            echo "No old dist folder found. Skipping removal."
          fi

      - name: Deploy new dist folder
        run: |
          if [ -d dist ]; then
            echo "New build found. Copying dist folder..."
            cp -r dist /var/www/html/followupdesk/
          else
            echo "Build folder 'dist' not found. Skipping deployment."
            exit 1
          fi